package(default_visibility = ["//visibility:public"])

#cc_binary(
#name = "grpc_async_server",
#srcs = ["grpc_async_server.cc"],
#deps = [
#"@com_github_grpc_grpc//:grpc++",
#"@com_github_grpc_grpc//:grpc++_reflection",
#"@jemalloc",
#],
#)
